version: '3.8'

services:
  
  db:
    build: ./db
    container_name: postgresql
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  server: 
    build: ./server
    restart: unless-stopped
    container_name: nodejs
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - db

  adminer:
    image: adminer
    container_name: adminer
    environment:
      ADMINER_DEFAULT_SERVER: postgresql
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  postgres_data: